# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - devel
  - bioc-devel
sudo: false
cache: packages
addons:
  apt:
    packages:
    - libudunits2-dev
